
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  backend:
    image: aeee/kittygram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: aeee/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      
  gateway:
    image: aeee/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 9000:80
